# 5. Computational Tools

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_wt_text = pd.read_pickle("./data/df_wt_text.pkl")
df_wt_text.shape

(178532, 35)

In [3]:
df_wt_text.head()

,Id,Detected_Info,Text,TextLower,Text_Category,Text_Occupancy,Text_Probability,Text_Centroid,ClientId,Client_Type,...,phone_number,is_phone,is_bigtext,Image_Occupancy,is_bigimage_text,is_agency,is_idealista_2,is_idealista_3,is_idealista_4,is_idealista_5
1,567017990,"{'text': '28', 'centroid': [715, 396], 'occupa...",28,28,numbers,0.17,0.993812,"[715, 396]",9202762585543,Profesional,...,[],False,False,0.0,False,False,False,False,False,False
6,567018037,"{'text': 'Re', 'centroid': [161, 1015], 'occup...",Re,re,letters,0.23,0.125165,"[161, 1015]",9202762585543,Profesional,...,[],False,False,0.0,False,False,False,False,False,False
9,567018724,"{'text': 'lv', 'centroid': [368, 1152], 'occup...",lv,lv,letters,2.75,0.001857,"[368, 1152]",9202762585543,Profesional,...,[],False,False,0.0,False,False,False,False,False,False
10,567028009,"{'text': '9e', 'centroid': [500, 195], 'occupa...",9e,9e,mixed,0.21,0.015480,"[500, 195]",9202762993528,Profesional,...,[],False,False,0.0,False,False,False,False,False,False
13,567022159,"{'text': 't', 'centroid': [350, 599], 'occupan...",t,t,letters,0.74,0.984563,"[350, 599]",9202753963841,Profesional,...,[],False,False,0.0,False,False,False,False,False,False

## 5.1. Statistical functions

### 5.1.1. Description: Summary statistics

In [5]:
df_wt_text.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 178532 entries, 1 to 155151
Data columns (total 35 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Id                 178532 non-null  int64
 1   Detected_Info      178532 non-null  object
 2   Text               178532 non-null  object
 3   TextLower          178532 non-null  object
 4   Text_Category      178532 non-null  object
 5   Text_Occupancy     178532 non-null  float64
 6   Text_Probability   178532 non-null  float64
 7   Text_Centroid      178532 non-null  object
 8   ClientId           178532 non-null  int64
 9   Client_Type        178532 non-null  object
 10  PropertyId         178532 non-null  object
 11  AgencyName         178532 non-null  object
 12  Detected_Info_Len  178532 non-null  int64
 13  Total_Occupancy    178532 non-null  float64
 14  Image_Width        178532 non-null  float64
 15  Image_Height       178532 non-null  float64
 16  ExecutionDate      178532 non-null  datetime64[ns]
 17  Date               178532 non-null  object
 18  Url                178532 non-null  object
 19  Text_Class         178532 non-null  object
 20  Text_Detected      178532 non-null  object
 21  is_url             178532 non-null  bool
 22  url_domain         2733 non-null    object
 23  url_suffix         2733 non-null    object
 24  is_email           178532 non-null  bool
 25  phone_number       178532 non-null  object
 26  is_phone           178532 non-null  object
 27  is_bigtext         178532 non-null  bool
 28  Image_Occupancy    178532 non-null  float64
 29  is_bigimage_text   178532 non-null  bool
 30  is_agency          178532 non-null  bool
 31  is_idealista_2     178532 non-null  bool
 32  is_idealista_3     178532 non-null  bool
 33  is_idealista_4     178532 non-null  bool
 34  is_idealista_5     178532 non-null  bool
dtypes: bool(9), datetime64[ns](1), float64(6), int64(3), object(16)
memory usage: 38.3+ MB

In [6]:
df_wt_text.describe()

,Id,Text_Occupancy,Text_Probability,ClientId,Detected_Info_Len,Total_Occupancy,Image_Width,Image_Height,Image_Occupancy
count,1.785320e+05,178532.000000,178532.000000,1.785320e+05,178532.000000,178532.00000,178532.000000,178532.000000,178532.000000
mean,5.675477e+08,1.706616,0.331027,8.718091e+12,5.044844,0.05832,1183.245536,890.838079,5.640411
std,4.568613e+05,2.698207,0.359837,1.950457e+12,6.746384,0.07532,434.106682,370.585079,11.319396
min,5.667797e+08,0.020000,0.000000,0.000000e+00,1.000000,0.00000,115.000000,60.000000,0.000000
25%,5.671473e+08,0.350000,0.009849,9.202753e+12,2.000000,0.01000,960.000000,694.000000,0.600000
50%,5.675504e+08,0.700000,0.169001,9.202755e+12,3.000000,0.03000,1200.000000,804.000000,2.390000
75%,5.680129e+08,1.790000,0.625918,9.202760e+12,5.000000,0.07000,1400.000000,1050.000000,6.780000
max,5.682333e+08,48.130000,0.999989,9.202764e+12,30.000000,1.30000,7952.000000,6000.000000,217.800000

In [7]:
df_wt_text['Client_Type_cat'] = df_wt_text.Client_Type.astype('category')

In [8]:
df_wt_text[['Total_Occupancy','Client_Type_cat']].describe(include = 'all')

        Total_Occupancy Client_Type_cat
count      178532.00000          178532
unique              NaN               2
top                 NaN     Profesional
freq                NaN          176529
mean            0.05832             NaN
std             0.07532             NaN
min             0.00000             NaN
25%             0.01000             NaN
50%             0.03000             NaN
75%             0.07000             NaN
max             1.30000             NaN

### 5.1.2. Cuts

In [33]:
df_wt_text['Text_Probability_cat'] = \
    pd.cut(df_wt_text.Text_Probability, [0.0,0.3,0.6,0.9,1.0], include_lowest=True)

df_wt_text.Text_Probability_cat

1            (0.9, 1.0]
6         (-0.001, 0.3]
9         (-0.001, 0.3]
10        (-0.001, 0.3]
13           (0.9, 1.0]
              ...
155147       (0.6, 0.9]
155148    (-0.001, 0.3]
155149    (-0.001, 0.3]
155150    (-0.001, 0.3]
155151    (-0.001, 0.3]
Name: Text_Probability_cat, Length: 178532, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.3] < (0.3, 0.6] < (0.6, 0.9] < (0.9, 1.0]]

In [34]:
df_wt_text[['Id','Text_Probability_cat']].groupby('Text_Probability_cat').count()

                          Id
Text_Probability_cat
(-0.001, 0.3]         105773
(0.3, 0.6]             26501
(0.6, 0.9]             21016
(0.9, 1.0]             25242

### 5.1.3. Percent change

Series and DataFrame have a method pct_change() to compute the percent change over a given number of periods (using fill_method to fill NA/null values before computing the percent change).

In [9]:
df_wt_text.Total_Occupancy.pct_change(periods=3)

1              NaN
6              NaN
9              NaN
10             inf
13             inf
            ...
155147   -0.250000
155148    0.000000
155149   -0.805556
155150    0.333333
155151   -0.666667
Name: Total_Occupancy, Length: 178532, dtype: float64

### 5.1.4. Covariance

Assuming the missing data are missing at random this results in an estimate for the covariance matrix which is unbiased. However, for many applications this estimate may not be acceptable because the estimated covariance matrix is not guaranteed to be positive semi-definite. This could lead to estimated correlations having absolute values which are greater than one, and/or a non-invertible covariance matrix.

In [10]:
df_wt_text.Total_Occupancy.cov(df_wt_text.Text_Probability)

0.001487015634605937

In [12]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

In [15]:
df_wt_text.select_dtypes(include=numerics).dropna().cov()

,Id,Text_Occupancy,Text_Probability,ClientId,Detected_Info_Len,Total_Occupancy,Image_Width,Image_Height,Image_Occupancy
Id,2.087222e+11,-2.452578e+04,5.484281e+03,-3.240377e+15,6.620378e+04,-3.206229e+00,-2.353576e+07,-1.612029e+07,-5.609422e+05
Text_Occupancy,-2.452578e+04,7.280321e+00,9.562120e-03,1.821963e+11,-2.778487e+00,8.238910e-02,2.406595e+01,-2.077950e+01,7.280512e+00
Text_Probability,5.484281e+03,9.562120e-03,1.294826e-01,-3.247475e+10,4.053418e-02,1.487016e-03,-4.935053e+00,-1.363049e+00,1.026434e-01
ClientId,-3.240377e+15,1.821963e+11,-3.247475e+10,3.804283e+24,6.944371e+11,9.764481e+09,-1.183104e+13,-1.097579e+13,1.230888e+12
Detected_Info_Len,6.620378e+04,-2.778487e+00,4.053418e-02,6.944371e+11,4.551370e+01,2.446142e-01,-3.727672e+02,-2.773394e+02,2.056313e+01
Total_Occupancy,-3.206229e+00,8.238910e-02,1.487016e-03,9.764481e+09,2.446142e-01,5.673050e-03,-2.233273e+00,-2.301129e+00,4.473397e-01
Image_Width,-2.353576e+07,2.406595e+01,-4.935053e+00,-1.183104e+13,-3.727672e+02,-2.233273e+00,1.884486e+05,1.190220e+05,-6.075244e+01
Image_Height,-1.612029e+07,-2.077950e+01,-1.363049e+00,-1.097579e+13,-2.773394e+02,-2.301129e+00,1.190220e+05,1.373333e+05,-1.666867e+02
Image_Occupancy,-5.609422e+05,7.280512e+00,1.026434e-01,1.230888e+12,2.056313e+01,4.473397e-01,-6.075244e+01,-1.666867e+02,1.281287e+02

### 5.1.5. Correlation

Correlation may be computed using the corr() method. Using the method parameter, several methods for computing correlations are provided:

- pearson (default): Standard correlation coefficient

- kendall: Kendall Tau correlation coefficient

- spearman: Spearman rank correlation coefficient

In [16]:
df_wt_text.select_dtypes(include=numerics).dropna().corr()

,Id,Text_Occupancy,Text_Probability,ClientId,Detected_Info_Len,Total_Occupancy,Image_Width,Image_Height,Image_Occupancy
Id,1.000000,-0.019896,0.033360,-0.003636,0.021480,-0.000093,-0.118672,-0.095214,-0.108470
Text_Occupancy,-0.019896,1.000000,0.009849,0.034620,-0.152638,0.405402,0.020546,-0.020781,0.238376
Text_Probability,0.033360,0.009849,1.000000,-0.046270,0.016697,0.054866,-0.031593,-0.010222,0.025200
ClientId,-0.003636,0.034620,-0.046270,1.000000,0.052775,0.066467,-0.013973,-0.015185,0.055752
Detected_Info_Len,0.021480,-0.152638,0.016697,0.052775,1.000000,0.481396,-0.127283,-0.110931,0.269274
Total_Occupancy,-0.000093,0.405402,0.054866,0.066467,0.481396,1.000000,-0.068303,-0.082441,0.524694
Image_Width,-0.118672,0.020546,-0.031593,-0.013973,-0.127283,-0.068303,1.000000,0.739849,-0.012364
Image_Height,-0.095214,-0.020781,-0.010222,-0.015185,-0.110931,-0.082441,0.739849,1.000000,-0.039737
Image_Occupancy,-0.108470,0.238376,0.025200,0.055752,0.269274,0.524694,-0.012364,-0.039737,1.000000

The method argument can also be a callable for a generic correlation calculation. In this case, it should be a single function that produces a single value from two ndarray inputs. Suppose we wanted to compute the correlation based on histogram intersection:

In [18]:
def histogram_intersection(a, b):
    return np.minimum(np.true_divide(a, a.sum()),
                      np.true_divide(b, b.sum())).sum()

In [19]:
df_wt_text.select_dtypes(include=numerics).corr(method=histogram_intersection)

,Id,Text_Occupancy,Text_Probability,ClientId,Detected_Info_Len,Total_Occupancy,Image_Width,Image_Height,Image_Occupancy
Id,1.000000,0.521948,0.523387,0.947640,0.573076,0.573873,0.872750,0.860497,0.500152
Text_Occupancy,0.521948,1.000000,0.389445,0.513919,0.344028,0.538174,0.510678,0.504017,0.479844
Text_Probability,0.523387,0.389445,1.000000,0.513503,0.400431,0.429739,0.506910,0.506667,0.383174
ClientId,0.947640,0.513919,0.513503,1.000000,0.561185,0.570552,0.848677,0.836351,0.498730
Detected_Info_Len,0.573076,0.344028,0.400431,0.561185,1.000000,0.611079,0.537981,0.540373,0.534530
Total_Occupancy,0.573873,0.538174,0.429739,0.570552,0.611079,1.000000,0.543534,0.535859,0.838758
Image_Width,0.872750,0.510678,0.506910,0.848677,0.537981,0.543534,1.000000,0.920265,0.476122
Image_Height,0.860497,0.504017,0.506667,0.836351,0.540373,0.535859,0.920265,1.000000,0.467959
Image_Occupancy,0.500152,0.479844,0.383174,0.498730,0.534530,0.838758,0.476122,0.467959,1.000000

A related method corrwith() is implemented on DataFrame to compute the correlation between like-labeled Series contained in different DataFrame objects.

In [23]:
index = ['a', 'b', 'c', 'd', 'e']
columns = ['one', 'two', 'three', 'four']

df1 = pd.DataFrame(np.random.randn(5, 4), index=index, columns=columns)
df2 = pd.DataFrame(np.random.randn(4, 4), index=index[:4], columns=columns)

df1.corrwith(df2)

one      0.920396
two      0.530617
three   -0.502914
four     0.186592
dtype: float64

In [28]:
df = pd.DataFrame()
df['one_1'] = df1.one
df['one_2'] = df2.one
df.corr()

          one_1     one_2
one_1  1.000000  0.920396
one_2  0.920396  1.000000

In [29]:
df1.corrwith(df2, axis=1)

a   -0.894961
b   -0.345283
c    0.833294
d    0.644376
e         NaN
dtype: float64

### 5.1.6. Data Ranking

In [ ]:
# TODO

## 5.2. Window Functions

In [ ]:
# TODO

## 5.3. Expanding windows

In [ ]:
# TODO

## 5.4. Exponentially weighted windows

In [ ]:
# TODO