In [1]:
import pandas as pd

In [25]:
df = pd.read_csv('sendgrid_events.csv', header = None)

In [3]:
df.head()

    0                                                  1
0   3  Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...
1   2  Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...
2  11  Mozilla/5.0 (Linux; Android 10; SM-A920F Build...
3   3  Mozilla/5.0 (Linux; Android 10; SM-A515F Build...
4  77  Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...

In [4]:
df[1]

0         Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...
1         Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...
2         Mozilla/5.0 (Linux; Android 10; SM-A920F Build...
3         Mozilla/5.0 (Linux; Android 10; SM-A515F Build...
4         Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...
                                ...
371310    Mozilla/5.0 (Linux; Android 11; RMX2040 Build/...
371311    Mozilla/5.0 (Linux; Android 11; SM-M315F Build...
371312    Mozilla/5.0 (Linux; Android 10; Armor X5 Build...
371313    Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...
371314    Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A52...
Name: 1, Length: 371315, dtype: object

In [9]:
pip install httpagentparser

Collecting httpagentparser
  Downloading httpagentparser-1.9.1.tar.gz (7.9 kB)
Building wheels for collected packages: httpagentparser
  Building wheel for httpagentparser (setup.py) ... done
  Created wheel for httpagentparser: filename=httpagentparser-1.9.1-py2.py3-none-any.whl size=7398 sha256=ed179edb8880d91a3b587b49d4b0bd1b8fafdfab92c7fd25054d28a4aff68185
  Stored in directory: /Users/cristobal.rojas/Library/Caches/pip/wheels/f0/39/27/903beb608b992909dccdb3c34ee1eed90c02b258c80e43032f
Successfully built httpagentparser
Installing collected packages: httpagentparser
Successfully installed httpagentparser-1.9.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import httpagentparser
s = "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/532.9 (KHTML, like Gecko) \
        Chrome/5.0.307.11 Safari/532.9"
print(httpagentparser.simple_detect(s))
('Linux', 'Chrome 5.0.307.11')

('Linux', 'Chrome 5.0.307.11')

('Linux', 'Chrome 5.0.307.11')

In [6]:
httpagentparser.simple_detect(df[1])

('Unknown OS', 'Unknown Browser')

In [7]:
ua = df[1].apply(lambda ua: httpagentparser.simple_detect(ua))

In [8]:
ua

0          (Android Linux 7.1.1, Chrome 90.0.4430.210)
1           (Android Linux 6.0.1, Chrome 93.0.4577.82)
2              (Android Linux 10, Chrome 93.0.4577.62)
3             (Android Linux 10, Chrome 91.0.4472.120)
4          (Android Linux 8.0.0, Chrome 92.0.4515.159)
                              ...
371310        (Android Linux 11, Chrome 92.0.4515.115)
371311         (Android Linux 11, Chrome 93.0.4577.62)
371312         (Android Linux 10, Chrome 94.0.4606.61)
371313    (Windows 7, Microsoft Internet Explorer 7.0)
371314        (Android Linux 11, Chrome 90.0.4430.210)
Name: 1, Length: 371315, dtype: object

In [9]:
df['uaserAgent'] = ua

In [10]:
df

,0,1,uaserAgent
0,3,Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...,"(Android Linux 7.1.1, Chrome 90.0.4430.210)"
1,2,Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...,"(Android Linux 6.0.1, Chrome 93.0.4577.82)"
2,11,Mozilla/5.0 (Linux; Android 10; SM-A920F Build...,"(Android Linux 10, Chrome 93.0.4577.62)"
3,3,Mozilla/5.0 (Linux; Android 10; SM-A515F Build...,"(Android Linux 10, Chrome 91.0.4472.120)"
4,77,Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...,"(Android Linux 8.0.0, Chrome 92.0.4515.159)"
...,...,...,...
371310,1,Mozilla/5.0 (Linux; Android 11; RMX2040 Build/...,"(Android Linux 11, Chrome 92.0.4515.115)"
371311,1,Mozilla/5.0 (Linux; Android 11; SM-M315F Build...,"(Android Linux 11, Chrome 93.0.4577.62)"
371312,1,Mozilla/5.0 (Linux; Android 10; Armor X5 Build...,"(Android Linux 10, Chrome 94.0.4606.61)"
371313,1,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,"(Windows 7, Microsoft Internet Explorer 7.0)"
371314,1,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A52...,"(Android Linux 11, Chrome 90.0.4430.210)"

In [11]:
ua2 = df[1].apply(lambda ua2: httpagentparser.detect(ua2))

In [12]:
ua2

0         {'platform': {'name': 'Android', 'version': '7...
1         {'platform': {'name': 'Android', 'version': '6...
2         {'platform': {'name': 'Android', 'version': '1...
3         {'platform': {'name': 'Android', 'version': '1...
4         {'platform': {'name': 'Android', 'version': '8...
                                ...
371310    {'platform': {'name': 'Android', 'version': '1...
371311    {'platform': {'name': 'Android', 'version': '1...
371312    {'platform': {'name': 'Android', 'version': '1...
371313    {'platform': {'name': 'Windows', 'version': '7...
371314    {'platform': {'name': 'Android', 'version': '1...
Name: 1, Length: 371315, dtype: object

In [13]:
df['uaserAgent2'] = ua2

In [14]:
df

,0,1,uaserAgent,uaserAgent2
0,3,Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...,"(Android Linux 7.1.1, Chrome 90.0.4430.210)","{'platform': {'name': 'Android', 'version': '7..."
1,2,Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...,"(Android Linux 6.0.1, Chrome 93.0.4577.82)","{'platform': {'name': 'Android', 'version': '6..."
2,11,Mozilla/5.0 (Linux; Android 10; SM-A920F Build...,"(Android Linux 10, Chrome 93.0.4577.62)","{'platform': {'name': 'Android', 'version': '1..."
3,3,Mozilla/5.0 (Linux; Android 10; SM-A515F Build...,"(Android Linux 10, Chrome 91.0.4472.120)","{'platform': {'name': 'Android', 'version': '1..."
4,77,Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...,"(Android Linux 8.0.0, Chrome 92.0.4515.159)","{'platform': {'name': 'Android', 'version': '8..."
...,...,...,...,...
371310,1,Mozilla/5.0 (Linux; Android 11; RMX2040 Build/...,"(Android Linux 11, Chrome 92.0.4515.115)","{'platform': {'name': 'Android', 'version': '1..."
371311,1,Mozilla/5.0 (Linux; Android 11; SM-M315F Build...,"(Android Linux 11, Chrome 93.0.4577.62)","{'platform': {'name': 'Android', 'version': '1..."
371312,1,Mozilla/5.0 (Linux; Android 10; Armor X5 Build...,"(Android Linux 10, Chrome 94.0.4606.61)","{'platform': {'name': 'Android', 'version': '1..."
371313,1,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,"(Windows 7, Microsoft Internet Explorer 7.0)","{'platform': {'name': 'Windows', 'version': '7..."
371314,1,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A52...,"(Android Linux 11, Chrome 90.0.4430.210)","{'platform': {'name': 'Android', 'version': '1..."

In [18]:
df['uaserAgent2'].apply(pd.Series)

,platform,os,bot,dist,browser,flavor
0,"{'name': 'Android', 'version': '7.1.1'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '7.1.1'}","{'name': 'Chrome', 'version': '90.0.4430.210'}",NaN
1,"{'name': 'Android', 'version': '6.0.1'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '6.0.1'}","{'name': 'Chrome', 'version': '93.0.4577.82'}",NaN
2,"{'name': 'Android', 'version': '10'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '10'}","{'name': 'Chrome', 'version': '93.0.4577.62'}",NaN
3,"{'name': 'Android', 'version': '10'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '10'}","{'name': 'Chrome', 'version': '91.0.4472.120'}",NaN
4,"{'name': 'Android', 'version': '8.0.0'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '8.0.0'}","{'name': 'Chrome', 'version': '92.0.4515.159'}",NaN
...,...,...,...,...,...,...
371310,"{'name': 'Android', 'version': '11'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '11'}","{'name': 'Chrome', 'version': '92.0.4515.115'}",NaN
371311,"{'name': 'Android', 'version': '11'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '11'}","{'name': 'Chrome', 'version': '93.0.4577.62'}",NaN
371312,"{'name': 'Android', 'version': '10'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '10'}","{'name': 'Chrome', 'version': '94.0.4606.61'}",NaN
371313,"{'name': 'Windows', 'version': '7'}","{'name': 'Windows', 'version': '7'}",False,NaN,"{'name': 'Microsoft Internet Explorer', 'versi...",NaN
371314,"{'name': 'Android', 'version': '11'}",{'name': 'Linux'},False,"{'name': 'Android', 'version': '11'}","{'name': 'Chrome', 'version': '90.0.4430.210'}",NaN

In [19]:
df2=pd.json_normalize(df['uaserAgent2'])

In [20]:
df_os=pd.concat([df[0],df2], axis=1)

In [21]:
df_os

,0,bot,platform.name,platform.version,os.name,dist.name,dist.version,browser.name,browser.version,os.version,flavor.name,flavor.version
0,3,False,Android,7.1.1,Linux,Android,7.1.1,Chrome,90.0.4430.210,NaN,NaN,NaN
1,2,False,Android,6.0.1,Linux,Android,6.0.1,Chrome,93.0.4577.82,NaN,NaN,NaN
2,11,False,Android,10,Linux,Android,10,Chrome,93.0.4577.62,NaN,NaN,NaN
3,3,False,Android,10,Linux,Android,10,Chrome,91.0.4472.120,NaN,NaN,NaN
4,77,False,Android,8.0.0,Linux,Android,8.0.0,Chrome,92.0.4515.159,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371310,1,False,Android,11,Linux,Android,11,Chrome,92.0.4515.115,NaN,NaN,NaN
371311,1,False,Android,11,Linux,Android,11,Chrome,93.0.4577.62,NaN,NaN,NaN
371312,1,False,Android,10,Linux,Android,10,Chrome,94.0.4606.61,NaN,NaN,NaN
371313,1,False,Windows,7,Windows,NaN,NaN,Microsoft Internet Explorer,7.0,7,NaN,NaN
371314,1,False,Android,11,Linux,Android,11,Chrome,90.0.4430.210,NaN,NaN,NaN

In [22]:
df_os=df_os.rename(columns={0: "Count", 'platform.name': "Platform", 'platform.version': "Platform_version"
                   ,'os.name': "Os_name", 'dist.name': "Dist_name", 'dist.version': "Dist_version"
                    ,'browser.name': "Browser_name", 'browser.version': "Browser_version", 'os.version': "Os_Version"
                    ,'flavor.name': "Flavor_name", 'flavor.version': "Flavor_version"
                   })

In [23]:
df_os.head()

,Count,bot,Platform,Platform_version,Os_name,Dist_name,Dist_version,Browser_name,Browser_version,Os_Version,Flavor_name,Flavor_version
0,3,False,Android,7.1.1,Linux,Android,7.1.1,Chrome,90.0.4430.210,NaN,NaN,NaN
1,2,False,Android,6.0.1,Linux,Android,6.0.1,Chrome,93.0.4577.82,NaN,NaN,NaN
2,11,False,Android,10,Linux,Android,10,Chrome,93.0.4577.62,NaN,NaN,NaN
3,3,False,Android,10,Linux,Android,10,Chrome,91.0.4472.120,NaN,NaN,NaN
4,77,False,Android,8.0.0,Linux,Android,8.0.0,Chrome,92.0.4515.159,NaN,NaN,NaN

In [24]:
df_os.to_csv('ijpush_apertura.csv')

In [45]:
pip install ua-parser

Collecting ua-parser
  Downloading ua_parser-0.10.0-py2.py3-none-any.whl (35 kB)
Installing collected packages: ua-parser
Successfully installed ua-parser-0.10.0
Note: you may need to restart the kernel to use updated packages.

In [26]:
df3

         0                                                  1
0        3  Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...
1        2  Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...
2       11  Mozilla/5.0 (Linux; Android 10; SM-A920F Build...
3        3  Mozilla/5.0 (Linux; Android 10; SM-A515F Build...
4       77  Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...
...     ..                                                ...
371310   1  Mozilla/5.0 (Linux; Android 11; RMX2040 Build/...
371311   1  Mozilla/5.0 (Linux; Android 11; SM-M315F Build...
371312   1  Mozilla/5.0 (Linux; Android 10; Armor X5 Build...
371313   1  Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...
371314   1  Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A52...

[371315 rows x 2 columns]

In [28]:
from ua_parser import user_agent_parser
import pprint

In [35]:
pp = pprint.PrettyPrinter(indent=4)

In [31]:
ua3 = df3[1].apply(lambda ua3: user_agent_parser.Parse(ua3))

In [33]:
ua3.head()

0    {'user_agent': {'family': 'Chrome Mobile WebVi...
1    {'user_agent': {'family': 'Chrome Mobile WebVi...
2    {'user_agent': {'family': 'Chrome Mobile WebVi...
3    {'user_agent': {'family': 'Chrome Mobile WebVi...
4    {'user_agent': {'family': 'Chrome Mobile WebVi...
Name: 1, dtype: object

In [36]:
pp.pprint(ua3)

0         {'user_agent': {'family': 'Chrome Mobile WebVi...
1         {'user_agent': {'family': 'Chrome Mobile WebVi...
2         {'user_agent': {'family': 'Chrome Mobile WebVi...
3         {'user_agent': {'family': 'Chrome Mobile WebVi...
4         {'user_agent': {'family': 'Chrome Mobile WebVi...
                                ...
371310    {'user_agent': {'family': 'Chrome Mobile WebVi...
371311    {'user_agent': {'family': 'Chrome Mobile WebVi...
371312    {'user_agent': {'family': 'Chrome Mobile WebVi...
371313    {'user_agent': {'family': 'Outlook', 'major': ...
371314    {'user_agent': {'family': 'Samsung Internet', ...
Name: 1, Length: 371315, dtype: object

In [37]:
df3['uaserAgent2'] = ua3

In [40]:
df3.head()

,0,1,uaserAgent2
0,3,Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...,{'user_agent': {'family': 'Chrome Mobile WebVi...
1,2,Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...,{'user_agent': {'family': 'Chrome Mobile WebVi...
2,11,Mozilla/5.0 (Linux; Android 10; SM-A920F Build...,{'user_agent': {'family': 'Chrome Mobile WebVi...
3,3,Mozilla/5.0 (Linux; Android 10; SM-A515F Build...,{'user_agent': {'family': 'Chrome Mobile WebVi...
4,77,Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...,{'user_agent': {'family': 'Chrome Mobile WebVi...

In [38]:
df_norm=pd.json_normalize(df3['uaserAgent2'])

In [39]:
df_norm

,string,user_agent.family,user_agent.major,user_agent.minor,user_agent.patch,os.family,os.major,os.minor,os.patch,os.patch_minor,device.family,device.brand,device.model
0,Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...,Chrome Mobile WebView,90,0,4430,Android,7,1,1,None,Samsung SM-J510F,Samsung,SM-J510F
1,Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...,Chrome Mobile WebView,93,0,4577,Android,6,0,1,None,Lenovo K33a48,Lenovo,K33a48
2,Mozilla/5.0 (Linux; Android 10; SM-A920F Build...,Chrome Mobile WebView,93,0,4577,Android,10,None,None,None,Samsung SM-A920F,Samsung,SM-A920F
3,Mozilla/5.0 (Linux; Android 10; SM-A515F Build...,Chrome Mobile WebView,91,0,4472,Android,10,None,None,None,Samsung SM-A515F,Samsung,SM-A515F
4,Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...,Chrome Mobile WebView,92,0,4515,Android,8,0,0,None,PRA-LX1,Huawei,PRA-LX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
371310,Mozilla/5.0 (Linux; Android 11; RMX2040 Build/...,Chrome Mobile WebView,92,0,4515,Android,11,None,None,None,RMX2040,Generic_Android,RMX2040
371311,Mozilla/5.0 (Linux; Android 11; SM-M315F Build...,Chrome Mobile WebView,93,0,4577,Android,11,None,None,None,Samsung SM-M315F,Samsung,SM-M315F
371312,Mozilla/5.0 (Linux; Android 10; Armor X5 Build...,Chrome Mobile WebView,94,0,4606,Android,10,None,None,None,Armor X5,Generic_Android,Armor X5
371313,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,Outlook,2010,None,None,Windows,7,None,None,None,Other,None,None
371314,Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-A52...,Samsung Internet,15,0,None,Android,11,None,None,None,Samsung SM-A528B,Samsung,SM-A528B

In [45]:
df_user_agent=pd.concat([df3[0],df_norm], axis=1)

In [46]:
df_user_agent=df_user_agent.rename(columns={0: "Count"
                   })

In [47]:
df_user_agent.head()

,Count,string,user_agent.family,user_agent.major,user_agent.minor,user_agent.patch,os.family,os.major,os.minor,os.patch,os.patch_minor,device.family,device.brand,device.model
0,3,Mozilla/5.0 (Linux; Android 7.1.1; SM-J510F Bu...,Chrome Mobile WebView,90,0,4430,Android,7,1,1,None,Samsung SM-J510F,Samsung,SM-J510F
1,2,Mozilla/5.0 (Linux; Android 6.0.1; Lenovo K33a...,Chrome Mobile WebView,93,0,4577,Android,6,0,1,None,Lenovo K33a48,Lenovo,K33a48
2,11,Mozilla/5.0 (Linux; Android 10; SM-A920F Build...,Chrome Mobile WebView,93,0,4577,Android,10,None,None,None,Samsung SM-A920F,Samsung,SM-A920F
3,3,Mozilla/5.0 (Linux; Android 10; SM-A515F Build...,Chrome Mobile WebView,91,0,4472,Android,10,None,None,None,Samsung SM-A515F,Samsung,SM-A515F
4,77,Mozilla/5.0 (Linux; Android 8.0.0; PRA-LX1 Bui...,Chrome Mobile WebView,92,0,4515,Android,8,0,0,None,PRA-LX1,Huawei,PRA-LX1

In [48]:
df_user_agent.to_csv('ijpush_apertura_2.csv')